### ISSUE TITLE
Error Related With Registery

### ISSUE THREAD

**Issue by bahadirarslan** [moodmosaic-attic/EmptyWebApiProjectTemplate#2]
I had installed template successfully and tried to create a new project but after selected to Empty Web API template i got error like below.

Package Installation Error
The project template has a reference to a missing Registy value. Could not find a Registry key with name 'AspNetMvc4VS11' under 'Software\Nuget\Repository'.

i am not sure what should i do to fix.
![Capture](https://f.cloud.github.com/assets/130344/77693/b558d596-6154-11e2-9f20-eff89007ce3f.PNG)

**Comment by moodmosaic** [comment]
Which version of Visual Studio do you use?

Are there any updates installed regarding the ASP.NET?

**Comment by bahadirarslan** [comment]
I am using Visual Studio 2012 with Update 1.

No, i didn't install any updates beside Visual Studio Update. Also i can create normal ASP.NET MVC 4 project and Web API

**Comment by bahadirarslan** [comment]
I figured out and fixed my problem.
i had replaced "AspNetMvc4VS11" with "WebStack4ToolsUpdate" at line 43 in EmptyWebApiProjectTemplate.vstemplate  file and rebuilded extension. And it worked :)

**Comment by moodmosaic** [comment]
That's great! Do you think that this solution could be generalized?

**Comment by bahadirarslan** [comment]
it is hard to say something but i got this value from system default templates; so we may generalize.

But it is strange that only i had problems with extension. I couldn't determine what factor caused this problem :(

**Comment by moodmosaic** [comment]
_Perhaps_ the Update 1 modified some templates?

**Comment by bahadirarslan** [comment]
May be, i am not so sure. But if someone looks for solution about this problem, here is the solution. 
After you became sure you can update the code.

Also, thanks for this template. It helped a lot :)

**Comment by moodmosaic** [comment]
You are welcome!

OK, I will have a look and if necessary I will also publish an update [here](http://visualstudiogallery.msdn.microsoft.com/a989a149-4bc3-4292-ac8a-5101ee1722d7) :)

**Comment by dfaroi** [comment]
Hi,

After installing this extension and using it same error.

Note : I'm using VS2010 SP1 with lastest ASP.Net MCV4.

Update:
I figured out and fixed my problem.
I had replaced "AspNetMvc4VS11" with "AspNetMvc4VS2010" in EmptyWebApiProjectTemplate.vstemplate file and rebuilded extension. 
And it worked :)

**Comment by moodmosaic** [comment]
@bahadirarslan, @dfaroi Thanks for reporting this!

FWIW, I just pushed a separate version for Visual Studio 2010. That version contains the _AspNetMvc4VS2010_ key, as you suggested :)
- The version for Visual Studio 2010 can be found [here](https://github.com/moodmosaic/EmptyWebApiProjectTemplate/tree/master/VS2010)
- The version for Visual Studio 2012 can be found [here](https://github.com/moodmosaic/EmptyWebApiProjectTemplate/tree/master/VS2012)

The version for Visual Studio 2012 is also uploaded on the Visual Studio gallery [page](http://visualstudiogallery.msdn.microsoft.com/a989a149-4bc3-4292-ac8a-5101ee1722d7/).
