### ISSUE TITLE
VS 2013 version?

### ISSUE THREAD

**Issue by k3davis** [moodmosaic-attic/EmptyWebApiProjectTemplate#5]
Will there be a version of this for VS2013?

**Comment by moodmosaic** [comment]
Good point :+1: 

Well, in Visual Studio 2013 there is only [one ASP.NET Project Type](http://blogs.msdn.com/b/mvpawardprogram/archive/2013/11/12/one-asp-net-welcome-to-the-web-development-buffet.aspx) and from there you proceed to a Project Template.

I haven't tested the existing methodology under this structural change. Perhaps it's doable, perhaps it's not...

**Comment by k3davis** [comment]
I don't think that article is current - I have two project types listed (one for web forms and one for MVC 4) - but the end result may be the same. I found this project searching on the same goals this seems to have been created under - too many useless or irrelevant files and packages in the default project type for web api projects. But for now I will keep manually culling them. ;) If you find this is doable in VS2013 I believe there would be interest.

**Comment by alexjamesbrown** [comment]
+1

**Comment by moodmosaic** [comment]
I must admit that I haven't kept up to date on the state of ASP.NET in Visual Studio 2013 and 2015. Is the ASP.NET project type(s) similar to the ones in 2012?

**Comment by k3davis** [comment]
I suspect the need for this has passed with VS2015 having radically different project types.
